### ISSUE TITLE
Two colons in URL confuses vmd while github is ok

### ISSUE THREAD

**Issue by hexmode** [yoshuawuyts/vmd#102]
Example file: https://github.com/seanchen/CategoryWatch/blob/master/README.md

Note the rendering of the url: https://www.mediawiki.org/wiki/Extension:CategoryWatch

In vmd, I get 
![image](https://user-images.githubusercontent.com/43581/28748290-0629a85c-7482-11e7-92d6-999af6b48e2e.png)

**Comment by josephfrazier** [comment]
I think this is the same bug as https://github.com/yoshuawuyts/vmd/issues/101

**Comment by hexmode** [comment]
Agreed.

**Comment by maxkueng** [comment]
Closing as duplicate of #101

**Comment by maxkueng** [comment]
It's fixed in vmd 1.29.2

**Comment by hexmode** [comment]
confirmed, tyvm
