### ISSUE TITLE
Support JSON Front Matter

### ISSUE THREAD

**Issue by maxkueng** [yoshuawuyts/vmd#113]
Upstream issue: wooorm/remark-frontmatter#2

Example:

```
{
    "title": "spf13-vim 3.0 release and new website",
    "description": "spf13-vim is a cross platform distribution of vim plugins and resources for Vim.",
    "tags": [ ".vimrc", "plugins", "spf13-vim", "vim" ],
    "date": "2012-04-06",
    "categories": [
        "Development",
        "VIM"
    ],
    "slug": "spf13-vim-3-0-release-and-new-website"
}

# Title

Content
```

**Comment by Flet** [comment]
Can this be closed now? :)

**Comment by maxkueng** [comment]
@Flet: No. Why? It stays open until it's implemented in vmd. There's an issue for it in wooorm/remark-frontmatter#2 and a pending pull request (wooorm/remark-frontmatter#3). Once this is merged and published we can implement it in vmd and close this issue.

**Comment by Flet** [comment]
Ah, I see now! Thank you for all your hard work on vmd :)
