### ISSUE TITLE
Add a window icon

### ISSUE THREAD

**Issue by maxkueng** [yoshuawuyts/vmd#12]
Would be cool to have a nice window icon that would be visible in the task bar & window title bar.

**Comment by maxkueng** [comment]
Maybe something that's based on [the Markdown Mark](https://github.com/dcurtis/markdown-mark).

![](https://camo.githubusercontent.com/e1bee1364b0b133574b19069155a23221051f9b9/687474703a2f2f636172676f2e64757374696e6375727469732e636f6d2f70726f6a656374732f6d646f776e5f6865616465722e706e673f33)

**Comment by maxkueng** [comment]
![vmd](https://cloud.githubusercontent.com/assets/168709/6200651/3f5d54f6-b482-11e4-8476-4bbf00322875.png) ?

**Comment by yoshuawuyts** [comment]
@maxkueng I like it! :D

**Comment by maxkueng** [comment]
![vmd-taskbar](https://cloud.githubusercontent.com/assets/168709/6200774/3b73c708-b487-11e4-8159-ff290f6f2eb4.png)
