### ISSUE TITLE
Open links in external browser

### ISSUE THREAD

**Issue by maxkueng** [yoshuawuyts/vmd#14]
Some thoughts and opinions on what links inside the rendered markdown document should do.

 - Links to external sites should open in the default desktop browser.
 - Links to sections within the same document (e.g. `#my-section-title`) should load in the same window.
 - Debatable: Relative links to other markdown documents in (e.g. `./CHANGELOG.md`)
 - Debatable: Links to external markdown documents (e.g. `github.com/other/project/README.md`)
 - Thinkable: How does one get back after opening a link that opens in the same window?

atom-shell has the [shell module](https://github.com/atom/atom-shell/blob/master/docs/api/shell.md) that could help with this. It also provides `shell.openExternal(url)`.

**Comment by yoshuawuyts** [comment]
I agree with most of your reasoning. I think relative paths could just spawn a new instance of `vmd`, keeping the original in place. Links to non-local paths should probably just be opened in the browser. What do you think?

**Comment by maxkueng** [comment]
> I think relative paths could just spawn a new instance of `vmd`, keeping the original in place.

Brilliant!

**Comment by aubinlorieux** [comment]
I agree it would be great if we can navigate between sections inside vmd and open external sites in the default browser.

I'm not really fan with creation of a new instance. If you write a doc with a table of content you don't want to open a new vmd window. 

It could be a parameter at launch `vmd --book table-of-content.md`

**Comment by yoshuawuyts** [comment]
@aubinlorieux that seems like a fair use case. Think it would make sense to have it be the default behavior since I can't think of any use case where it would be blocking. Maybe adding `shift + click` to open a new window would be nice. That way `vmd` also stays consistent with existing browser behavior.

**Comment by aubinlorieux** [comment]
> Maybe adding `shift + click` to open a new window would be nice.

Yes it would be nice !

**Comment by maxkueng** [comment]
I agree that it can be weird if relative links to other Markdown documents spawn a new instance / window. But if any links other than same-page-jumps between sections open in the same window there has to be a way to get back to the previous document. Personally I really like that `vmd` has no buttons and such.

Leveraging `Shift + Click`, or the middle mouse button may be an option to provide alternative behaviors. Good idea.

**Comment by mattdesl** [comment]
You could add global shortcuts to handle back/next buttons without adding any additional UI.

**Comment by DeeplyUncertain** [comment]
Just checking to see if there yet exists a feature that works for section links/internal links.  I've been trying to make a functional table of contents without having to use a browser, but nothing's really worked yet.  I'm rather new to Markdown, though.

**Comment by xHN35RQ** [comment]
@DeeplyUncertain until a solution is added to `vmd` consider using [`shiba`](https://github.com/rhysd/Shiba) which offers internal linking between local markdown documents. Hopefully that helps you.
