### ISSUE TITLE
when hovering over links, path is not previewed

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/vmd#17]
When hovering over a link there's no preview like it happens in the browser. I think it's useful to verify that links indeed point to the intended location.

**Comment by maxkueng** [comment]
It was doable entirely in CSS. Woot!

![vmd-linkhover](https://cloud.githubusercontent.com/assets/168709/6306916/b1344026-b937-11e4-9986-7348e2211c02.png)

**Comment by maxkueng** [comment]
v1.4.0

**Comment by yoshuawuyts** [comment]
:clap: :clap: Nice work!
