### ISSUE TITLE
pipe stdin to vmd

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/vmd#18]
e.g. be able to do this:
```sh
cat README.md | vmd
```

Doesn't make `vmd` a pager yet, but does allow for more unixy actions. Also maybe detect if in TTY to pipe to stdout. Not sure what the added value would be over something like `cat`, but playing ball with cli tools is a good thing imo.

```sh
vmd README.md | grep -C 3 foo > file.md
```

**Comment by akileez** [comment]
maybe you could use something like [get-stdin](https://github.com/sindresorhus/get-stdin)

**Comment by yoshuawuyts** [comment]
@akileez Oh, that's really useful. Thanks for sharing!

**Comment by akileez** [comment]
my pleasure.

**Comment by gummesson** [comment]
There's also [read-file-stdin](https://github.com/ianstormtaylor/read-file-stdin) and [write-file-stdout](https://github.com/ianstormtaylor/write-file-stdout), which work incredibly well.

**Comment by maxkueng** [comment]
read-file-stdin looks like it's worth considering. The source is only couple lines plus a dependency. It takes a file and falls back to `stdin` if it doesn't exist. It's more like "read-file-**or**-stdin".  So we wouldn't have to do `if`s and all that. The module does it for us. Good find!

**Comment by mattdesl** [comment]
:+1: 

Would enable the following coolness:

```npm view browserify readme | vmd```

**Comment by mattdesl** [comment]
pushed in `1.7.0` :+1:

**Comment by maxkueng** [comment]
:dancers:

**Comment by yoshuawuyts** [comment]
🙌🔥🍉
