### ISSUE TITLE
Stylesheet

### ISSUE THREAD

**Issue by aubinlrx** [yoshuawuyts/vmd#19]
It would be nice to be able to modify the defaults stylesheets to use alternative one.

`vmd README.md --style=/folderCss/styles.css"`

or with a config file `vmd.conf` in the .md directory

**Comment by yoshuawuyts** [comment]
Sounds reasonable. Before this can be added the source needs to be cleaned up a little though, which I'm hoping to do somewhere this week. Would you be willing to create a PR that adds this after that? Thanks!

**Comment by aubinlorieux** [comment]
Yes i will try to look at somewhere next week
