### ISSUE TITLE
Support GitHub style emoji

### ISSUE THREAD

**Issue by rgbkrk** [yoshuawuyts/vmd#27]
![screenshot 2015-06-19 08 06 11](https://cloud.githubusercontent.com/assets/836375/8253917/ccfc95ae-1659-11e5-8525-cc1f95b1f8c1.png)

/cc @blink1073 @carreau

**Comment by rgbkrk** [comment]
Actually, it looks like [`roaster`](https://www.npmjs.com/package/roaster) does this out of the box. It's the same one Atom uses.

**Comment by blink1073** [comment]
@rgbkrk, that is a nicely presented issue :smile:

**Comment by yoshuawuyts** [comment]
Oooh, `roaster` looks neat! :grin:
