### ISSUE TITLE
Better highlighting

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/vmd#33]
Following up on #32, we might want to improve the syntax highlighting. GitHub uses `pygments`, so https://github.com/rvagg/node-pygmentize-bundled might be a good option. Any other suggestions / options? I've tried https://github.com/atom/highlights once, but I remember it being slightly different from the github.com's styles.

**Comment by roryokane** [comment]
GitHub hasn’t used Pygments for years. GitHub [currently uses][gh-help] its own [Linguist] library for syntax highlighting.

Linguist is written in Ruby. The `tmLanguage` files linked in its [`vendor/grammars`][grammars] directory define how it highlights each language.

[gh-help]: https://help.github.com/articles/my-repository-is-marked-as-the-wrong-language/
[Linguist]: https://github.com/github/linguist
[grammars]: https://github.com/github/linguist/tree/master/vendor/grammars

**Comment by maxkueng** [comment]
I'm closing this since the highlighting is totally sufficient and there are no concrete ideas for better highlighters that don't depend on other scripting environments.
