### ISSUE TITLE
Won't display &#8984; (apple command symbol)

### ISSUE THREAD

**Issue by xHN35RQ** [yoshuawuyts/vmd#34]
I am writing keyboard reference documentation, and need to use `&#8984;` for the Apple Command Symbol. VMD only displays a box instead of &#8984;

Any way to fix this?

**Comment by maxkueng** [comment]
I'm guessing the font doesn't support that character. I tried both `&#8984;` and `⌘` in a Markdown document and they both show up as a square in vmd. Though, if you copy the square from vmd and paste it into something that supports the character it shows a ⌘. So the transformation from `&#8984;` to `⌘` does work.

**Comment by xHN35RQ** [comment]
Ok, I see that now. I get the same behavior here. What font is being used in VMD? I'm on Linux and perhaps the wrong font is being used.

**Comment by maxkueng** [comment]
I'm also on Linux. The font family is 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, freesans, sans-serif. The definition comes from the github-markdown-css package. On my system it renders with `Liberation Sans` which means it fell all the way through to `sans-serif`.

**Comment by xHN35RQ** [comment]
I went into github-markdown-css and manually set the font to "Noto Sans" to see what would happen, and it's having the same problem. `&#8984;` is rendered as a square. So I'm guessing it's not the github-markdown-css package, but rather how VMD is interpreting the HTML entity code?

**Comment by maxkueng** [comment]
I just checked on in Chrome on GitHub and it also falls through to Liberation Sans but it does render the characters properly. You you're right. It must be something in vmd. Or in Electron.

**Comment by xHN35RQ** [comment]
Oh sure, maybe it's an electron issue.

**Comment by yoshuawuyts** [comment]
On OS X:
- `⌘` renders fine
- `&#8984` is interpreted as a literal

`marked` doesn't seem to allow encoding to be configured, [`mdast-html`](https://github.com/wooorm/mdast-html#configuration) seems to allow it. I've been thinking of switching for a while; maybe this would work with `mdast`.

**Comment by wooorm** [comment]
:+1: 😉 

Maybe use [mdast-react](https://github.com/mapbox/mdast-react) (which could easily be forked for vdom?) for speed though.

**Comment by xHN35RQ** [comment]
cool. thanks for looking at this issue. It's helpful to me.

**Comment by xHN35RQ** [comment]
[Markn](https://github.com/minodisk/markn) uses https://github.com/wooorm/mdast and https://github.com/mizchi/md2react

**Comment by xHN35RQ** [comment]
Just tested this again, and everything works fine now. `&#8984;` renders correctly as &#8984;
