### ISSUE TITLE
Default to README.md

### ISSUE THREAD

**Issue by alexanderGugel** [yoshuawuyts/vmd#36]
Would be nice if it would default to `README.md` when no file name is supplied.

**Comment by maxkueng** [comment]
:+1:

**Comment by maxkueng** [comment]
It currently defaults to `stdin` if no file path is supplied. If there is a way to distinguish between no file name + stdin  and no file name + no stdin then that seems doable.

@alexanderGugel: If you know how to do it would you want to give it a try?
