### ISSUE TITLE
Necessary feature: zoom

### ISSUE THREAD

**Issue by DeeplyUncertain** [yoshuawuyts/vmd#43]
This pager is inaccessible to me, and others, without the ability to change the default text size or zoom.

**Comment by maxkueng** [comment]
Sounds reasonable. What do you think is the better solution? Just increase the text size, or actually zoom (increase everything) just like browsers do it?

**Comment by maxkueng** [comment]
You can now zoom in and out using the menu or `Ctrl/Cmd` and `+`, `-`, or `0`.

```sh
npm install -g vmd@1.10.0
```

**Comment by maxkueng** [comment]
```sh
npm install -g vmd@1.11.0
```

You can now save your preferred zoom factor in a config file so it will always be the way you want it when ever you start vmd. Check out the [section in the README](https://github.com/yoshuawuyts/vmd/blob/master/README.md#configuration) on how to do it or read it directly in vmd:  
`npm view vmd readme | vmd`

**Comment by yoshuawuyts** [comment]
:tada:

**Comment by DeeplyUncertain** [comment]
Wow, I did not expect such a quick and thorough resolution.  Thanks
