### ISSUE TITLE
Erro in install on OSX

### ISSUE THREAD

**Issue by jonatasfreitasv** [yoshuawuyts/vmd#46]
Downloading electron-v0.30.6-darwin-x64.zip
[============================================>] 100.0% of 35.32 MB (780.66 kB/s)
/usr/local/lib/node_modules/vmd/node_modules/electron-prebuilt/install.js:15
  throw err
        ^
Error: EACCES, rename '/usr/local/lib/node_modules/vmd/node_modules/electron-prebuilt/electron-tmp-download-4550-1441578968203/electron-v0.30.6-darwin-x64.zip'
    at Error (native)
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "vmd"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.30.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.30.6 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jonatasfreitas/npm-debug.log

**Comment by xHN35RQ** [comment]
until you get this fixed, you might try out https://github.com/rhysd/shiba which is based on vmd.

**Comment by yoshuawuyts** [comment]
@jonatasfreitasv That's odd. I've tried recreating your issue, but `vmd` on `node@0.12.4` with `npm@2.10.1` installs fine on my machine. Could you try running `sudo npm install vmd -g`? I suspect it might because of a permission issue, using https://github.com/creationix/nvm might help with that if you aren't using it already.

If sudo fails, could you post the `npm-debug.log` file of the output? Thanks!

**Comment by maxkueng** [comment]
No response in a while and nobody else seems to have this problem.

I'm closing it. We can reopen the issue if it happens again.

**Comment by onmyway133** [comment]
I'm having this issue too

```
sudo npm install vmd -g              1 ↵
/usr/local/bin/vmd -> /usr/local/lib/node_modules/vmd/bin/cli.js

> fsevents@1.1.1 install /usr/local/lib/node_modules/vmd/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/vmd/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> electron@1.4.15 postinstall /usr/local/lib/node_modules/vmd/node_modules/electron
> node install.js

/usr/local/lib/node_modules/vmd/node_modules/electron/install.js:46
  throw err
  ^

Error: EACCES: permission denied, link '/usr/local/lib/node_modules/vmd/node_modules/electron/electron-tmp-download-48563-1490565768994/electron-v1.4.15-darwin-x64.zip' -> '/Users/khoa/.electron/electron-v1.4.15-darwin-x64.zip'
    at Error (native)
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "vmd" "-g"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.15 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.4.15 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/khoa/XcodeProject3/npm-debug.log
npm ERR! code 1
```

**Comment by yoshuawuyts** [comment]
Looks like your node is setup wrong somehow; consider installing it through
nvm (node version manager) to make sure the permissions are alright

**Comment by onmyway133** [comment]
@jonatasfreitasv Hi, my `node -v` shows `v6.9.5`, is that correct version? I will try with nvm too

**Comment by yoshuawuyts** [comment]
Hey yeah it's not the version that matters, it's the filesystem permissions
that are wrong. You can always try and fix it yourself with some googling,
but I've found nvm to be more convenient in the past. Totally up to you of
course as either approach is valid

**Comment by onmyway133** [comment]
@yoshuawuyts I use `nvm` and I can install `vmd` now
