### ISSUE TITLE
Images are not loading

### ISSUE THREAD

**Issue by maxkueng** [yoshuawuyts/vmd#6]
Images with a relative path to the Markdown file won't load.

It only works when inside the vmd repository and `./cli.js README.md`. But it doesn't work with anything else.

**Comment by matthewdias** [comment]
this is still broken for me

**Comment by maxkueng** [comment]
@matthewdias Can you provide an example to reproduce the problem? Both `![alt text](./images/image.jpg)` and `![alt text](images/image.jpg)` (with and without `./`) work fine for me.

Are you using Windows? I don't thing we have ever tested vmd on Windows.

**Comment by matthewdias** [comment]
I'm using os x, and a simple ![](/images/devtools-full.gif) doesn't work.

**Comment by matthewdias** [comment]
Ah, I guess the `/images` would be the problem. Many people do this in git repos to reference the root directory of the repo.

**Comment by maxkueng** [comment]
Oh, well. `/images/devtools-full.gif` is an absolute path so the `images` directory is expected to be in your system root. But I see the problem though. It's probably very rare that somebody wants to use an actual absolute path in a markdown document and your use-case is likely much more common.

It's debatable whether we want to change this. But it should happen in a new ticket and stay open for a few days for people to add their opinions because changing this would mean that absolute paths won't work any more.
