### ISSUE TITLE
Show/hide/enable/disable menu items based on context

### ISSUE THREAD

**Issue by maxkueng** [yoshuawuyts/vmd#61]
Some menu items in both the context menu and the application menu should only be enabled when certain conditions are met, others should be hidden.

Examples:

 - `Edit -> Copy` should only be visible when some text is selected
 - `History -> Back` should only be enabled if it's possible to go back
 - `History -> Forward` should only be enabled if it's possible to go forward

**Comment by Flet** [comment]
Wow, thanks for all the contributions to vmd @maxkueng!

**Comment by maxkueng** [comment]
Thanks @Flet! I'm doing it because I'm having fun.
