### ISSUE TITLE
Image tags no longer showing

### ISSUE THREAD

**Issue by mattdesl** [yoshuawuyts/vmd#66]
I just updated to latest vmd and `<img>` tags don't seem to be showing anymore. Screenshot attached:

(look near the bottom)

<img width="563" alt="screen shot 2016-01-06 at 11 48 29 am" src="https://cloud.githubusercontent.com/assets/1383811/12148263/7625e086-b46b-11e5-9b56-de4fe540d047.png">

**Comment by maxkueng** [comment]
Interesting. It seems not all `<img />` tags are affected. I did `npm view budo readme | vmd` and the first image that is inside the `<center>` tag doesn't work but the second one (`src="http://i.imgur.com/ZlfJL1i.png"`) works, and the third image (`src="https://nodei.co/npm/budo.png"`) works too.

Could have something to do with the latest update uf the [marked](https://github.com/chjj/marked). I'll check it out.

**Comment by maxkueng** [comment]
fixed in `vmd@1.21.2`
