### ISSUE TITLE
Search within document

### ISSUE THREAD

**Issue by maxkueng** [yoshuawuyts/vmd#73]
Would be nice to be able to search within a document.

I was thinking about the following functionality, similar to how it works in browsers:
- Press `Control/Cmd+F` or select "Search" from a menu, type search query.
- Highlight all results (preferably as you type).
- Jump back and forth between results.
- Press `Esc` to hide search input and clear results.

Things to check out:
- `webContents.findInPage(text[, options])` ([docs](https://github.com/atom/electron/blob/master/docs/api/web-contents.md#webcontentsfindinpagetext-options))
- `webContents.stopFindInPage(action)` ([docs](https://github.com/atom/electron/blob/master/docs/api/web-contents.md#webcontentsstopfindinpageaction))

**Comment by xaviervalarino** [comment]
As mentioned in #91, it would be nice to be able to trigger a text search by using the `/` key (the same key used for search in Vi/Vim)

**Comment by markbrown4** [comment]
I'm happy to make a start on this feature.

**Comment by maxkueng** [comment]
@markbrown4: That would be awesome!

**Comment by maxkueng** [comment]
Someone had already made a [pretty awesome module](https://github.com/rhysd/electron-in-page-search) (thanks @rhysd!) and adding it was straight-forward.

For now it uses the module's default styles and looks a little "rough" but it's usable and really helps a lot already.

Hit `Ctrl+F` or `Cmd+F` to open the search dialog.

vmd 1.31.0 is on npm and [packaged builds](https://github.com/yoshuawuyts/vmd/releases) will be ready in a few minutes.

**Comment by josephfrazier** [comment]
> * Press Esc to hide search input and clear results.

Do you know how difficult it would be to implement this? I love the new search feature, but I instinctively press Escape to stop searching, only to have the entire window close. It looks like `electron-in-page-search` has some relevant code, so hopefully it's not too hard to wire up: https://github.com/rhysd/electron-in-page-search/blob/7e26dba74bc687a715a7be0634413278c6ea4460/src/search-window.ts#L50-L52
