### ISSUE TITLE
Support html/pdf generation

### ISSUE THREAD

**Issue by rakeen** [yoshuawuyts/vmd#79]
Being able to generate html/pdf files from the terminal would be great.  
```sh
vmd readme.md > readme.html
vmd readme.md > readme.pdf
```

**Comment by mattdesl** [comment]
This would be cool but I don't see why it has to be part of `vmd`? I think another tool like `md-to-pdf` might be better, if it doesn't already exist. :smile:

**Comment by davidmarkclements** [comment]
@rakeen - http://npm.im/hyperpdf
