### ISSUE TITLE
Treat git repo root as root for relative file paths?

### ISSUE THREAD

**Issue by matthewdias** [yoshuawuyts/vmd#83]
Creating this issue for discussion. See recent comments on #6.

**Comment by matthewdias** [comment]
Would it make sense to only apply this for files named with standard repo names (`README.md`, `CONTRIBUTING.md`, etc), and follow the existing behaviour otherwise?

**Comment by yoshuawuyts** [comment]
I think treating leading slashes as relative to the repository, rather than the OS is a smell. I see no reason why `./my-image.jpg` or `my-image.jpg` doesn't suffice. `/my-image.jpg` reads as if it's part of root; whereas it's not.

**Comment by matthewdias** [comment]
Yeah, I agree that's the right way to specify paths. Only reason I opened this for discussion is that many others do this in their git repos, which means that when others clone and attempt to use vmd to view the readme, the images don't work. It's not totally necessary so use your judgement if you think this should be implemented or not.

**Comment by CThuleHansen** [comment]
I cannot get an image to show, even though it works on github.
`![C++ Component connections](notes/hybridCosimulation-framework.png)
`
I have also tried `./notes/...`, `/notes/...` `~/notes/...` etc.
The readme.md is in root, and notes is a folder in root.

I do not really understand the conclusion of this issue - how do I specify relative paths?
