### ISSUE TITLE
Support org-mode format

### ISSUE THREAD

**Issue by agzam** [yoshuawuyts/vmd#97]
Org-mode is a quite popular format. Github supports it. Would it be possible to build support for it in the app? That'd be awesome!

**Comment by maxkueng** [comment]
Hey @agzam,

that's a cool idea but I think it's a bit out of scope for vmd. GitHub supports a number of "markup" formats: Markdown, Textile, RDoc, Org mode, Creole, MediaWiki, reStructuredText, AsciiDoc, and Perl Pod. 

If we added Org mode it would make sense to also support all the others. But supporting multiple different markups would require significant architectural changes in the code. And making all of them look like they do on GitHub would require additional CSS work and a lot of testing and attention to detail.

It'd be fairly simple if we could use [github/markup](https://github.com/github/markup) but that would make Ruby a dependency of vmd and users would have to make sure that they have installed a compatible version of it before installing vmd. I would prefer it if all of vmd's dependencies could be resolved through npm.

**Comment by mightyiam** [comment]
> " I would prefer it if all of vmd's dependencies could be resolved through npm"

👍
